export const ADD__DRAGGING__ITEM = "ADD__DRAGGING__ITEM";
export const REMOVE__DRAGGING__ITEM = "REMOVE__DRAGGING__ITEM";

export const ADD__LIST__ITEM = "ADD__LIST__ITEM";
export const REMOVE__LIST__ITEM = "REMOVE__LIST__ITEM";
export const UPDATA__LIST__FROM_STROAGE = "UPDATA__LIST__FROM_STROAGE";

export const UPDATE__CLIENTY__FOR__ABS = "UPDATE__CLIENTY__FOR__ABS";
